pipeline {
  agent any
 
  tools {nodejs "NodeJS 22"}
 
    stages {
        stage('Clonar repositorio') {
            steps {
                git 'https://github.com/roxsross/node-app-devops.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado'
        }
    }
}